### ISSUE TITLE
chrash

### ISSUE THREAD

**Issue by seleskidraaiorgels** [barrelorgandiscovery/aprintproject#111]
when i want to go to puchn windows control it wil chrash 
[hs_err_pid10488.log](https://github.com/barrelorgandiscovery/aprintproject/files/13232241/hs_err_pid10488.log)
[hs_err_pid12944.log](https://github.com/barrelorgandiscovery/aprintproject/files/13232242/hs_err_pid12944.log)

**Comment by frett27** [comment]
Thank's for the feedback, 
Seems the native access to serial port is faulty, on this OS
just updated the serial port library, that previously seems a bit old (since 2014), and then qualify the new behviour
