### ISSUE TITLE
Perfo laser, sur les tirets, 

### ISSUE THREAD

**Issue by frett27** [barrelorgandiscovery/aprintproject#33]
Actuellement, les tirets sont perforés avec les passes multiples, 
voir pour :
- paramétrer la vitesse pour les tirets (en plus de la puissance)

On fait pas ?

**Comment by music59940** [comment]
Voir aussi pour ne faire qu'une seule passe sur les tirets si l'option passe additionnel est sélectionné.

**Comment by frett27** [comment]
@music59940, Yann, as tu testé les autres éléments ?

**Comment by frett27** [comment]
Ajout d'une configuration pour les tirets (une passe ou plusieures), conservation d'une passe en utilisant la puissance à mi chaire pour les traits continus (recto, verso)
