### ISSUE TITLE
Souhait de conservation de la taille des fenetre

### ISSUE THREAD

**Issue by autopanphone** [barrelorgandiscovery/aprintproject#98]
Lors de choix de fichiers dans model editor, il n'est pas facile d'avoir une bonne vision de la liste des fichiers, spécialement lorsqu'il y a une liste longue

en tant que : utilisateur d'aprint
lorsque : je choisit un fichier dans une boite, il m'est difficile de sélectionner le fichier, car la fenetre est trop petite, 
ainsi: je pourrai me simplifier la vision et l'utilisation, en me concentrant sur la liste et non les fenetre

**Comment by frett27** [comment]
Ajout d'un stockage de la taille de la fenetre pour les fichiers
